image: eu.gcr.io/speedy-lattice-334/chromium-xvfb:0.1.0

cache:
    paths:
        - node_modules/

variables:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    CYPRESS_INSTALL_BINARY: 0
    CHROMIUM_BIN: /usr/bin/chromium-browser

stages:
    - test
    # - publish

before_script:
    # - cp _.npm_rc ~/.npmrc
    - apt-get update
    - apt-get -qq -y install wget #install wget
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
    - source $HOME/.bashrc
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use #load nvm
    - eval "[ -f .nvmrc ] && nvm install || nvm install stable" #install node
    - nvm install 12.20.1
    - nvm use 12.20.1

unit_tests:
    stage: test
    tags:
        - frontend
        - docker
    script:
        - npm install --silent
        # - npm run bower-install -- --silent
        - npm run build
        - npm run test -- --coverage --watchAll=false
        - git fetch origin master
        - git checkout master
        - git checkout -B "$CI_BUILD_REF_NAME"
        # - npm run commitlint

    artifacts:
        name: '${CI_PROJECT_NAME}_${CI_BUILD_ID}'
        paths:
            - build/
            - coverage/
            - junitxml_report/
        expire_in: 1 hour
# publish:
#   stage: publish
#   tags:
#     - docker
#     - frontend
#   script:
#     - npm install --silent
#     - npm run bower-install -- --silent
#     - npm run build
#     - npm publish
#   only:
#     - master
#   except:
#     variables:
#       - $CI_PIPELINE_SOURCE == "schedule"
#   when: manual
